version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): update github-actions versions"

  - package-ecosystem: "terraform"
    directories:
      - "/samples/document-explorer/terraform-config-backend"
      - "/samples/document-explorer/terraform-config-frontend"
      - "/samples/bedrock-agent"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): update terraform modules"

  - package-ecosystem: "pip"
    directories:
      - "/samples/document-explorer/client_app"
      - "/samples/bedrock-agent/lambda/action-group"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): update pip packages"

  - package-ecosystem: "docker"
    directories:
      - "/samples/document-explorer/client_app"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): update docker images"