[[pages]]
name = "Document Explorer"
icon = "📁"
is_section = true

[[pages]]
path = "pages/1_doc_explorer_home.py"
name = "Home"
icon = "🏠"


[[pages]]
path = "pages/2_Select_Document.py"
name = "Select Document"
icon = "📃"

[[pages]]
path = "pages/3_Q&A.py"
name = "Q&A"
icon = "💬"

[[pages]]
path = "pages/4_Summary.py"
name = "Summary"
icon = "🏷️"

[[pages]]
path = "pages/5_Visual_Q&A.py"
name = "Visual Q&A"
icon = "👁️‍🗨️"