name: bandit
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
permissions: read-all
jobs:
  bandit:
    name: bandit/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      security-events: write
      actions: read
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
        with:
          python-version: 3.x
      - name: Run Bandit
        run: pip install bandit && bandit --recursive --format html --output bandit-report.html --exit-zero .
      - name: Store Bandit as Artifact
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
        with:
          name: bandit-report.html
          path: bandit-report.html