name: bandit
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
permissions: read-all
jobs:
  bandit:
    name: bandit/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      security-events: write
      actions: read
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        with:
          python-version: 3.x
      - name: Run Bandit
        run: pip install bandit && bandit --recursive --format html --output bandit-report.html --exit-zero .
      - name: Store Bandit as Artifact
        uses: actions/upload-artifact@184d73b71b93c222403b2e7f1ffebe4508014249
        with:
          name: bandit-report.html
          path: bandit-report.html