name: checkov
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  bandit:
    name: checkov/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      security-events: write
      actions: read
    steps:
      - name: Checkout project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: 3.x
      - name: Run Checkov
        run: pip install checkov && checkov --quiet --output cli --output junitxml --output-file-path console,checkov.xml --directory .
      - name: Store Checkov as Artifact
        uses: actions/upload-artifact@18bf333cd2249fbbbdb605fd9d9ed57efd7adf34
        with:
          name: checkov.xml
          path: checkov.xml
