name: checkov
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
permissions: read-all
jobs:
  bandit:
    name: checkov/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      security-events: write
      actions: read
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        with:
          python-version: 3.x
      - name: Run Checkov
        run: pip install checkov && ( checkov --quiet --output cli --output json --output-file-path console,checkov.json --directory . || echo "checkov non-zero $?" )
      - name: Store Checkov as Artifact
        uses: actions/upload-artifact@184d73b71b93c222403b2e7f1ffebe4508014249
        with:
          name: checkov.json
          path: checkov.json
