name: checkov
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
permissions: read-all
jobs:
  bandit:
    name: checkov/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      security-events: write
      actions: read
    steps:
      - name: Checkout project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: 3.x
      - name: Run Checkov
        run: pip install checkov && ( checkov --quiet --output cli --output json --output-file-path console,checkov.json --directory . || echo "checkov non-zero $?" )
      - name: Store Checkov as Artifact
        uses: actions/upload-artifact@184d73b71b93c222403b2e7f1ffebe4508014249
        with:
          name: checkov.json
          path: checkov.json
