name: checkov
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
permissions: read-all
jobs:
  bandit:
    name: checkov/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      security-events: write
      actions: read
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: 3.x
      - name: Run Checkov
        run: pip install checkov && ( checkov --quiet --output cli --output json --output-file-path console,checkov.json --directory . || echo "checkov non-zero $?" )
      - name: Store Checkov as Artifact
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
        with:
          name: checkov.json
          path: checkov.json
