name: semgrep
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
permissions: read-all
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      security-events: write
      actions: read
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Run Semgrep CI
        run: semgrep scan --verbose --json --output=semgrep.json
      - name: Store Semgrep as Artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: semgrep.json
          path: semgrep.json
    container:
      image: semgrep/semgrep